### ISSUE TITLE
Training on multiple GPUs

### ISSUE THREAD

**Issue by chinnusai25** [athn-nik/teach#11]
Hey, currently the training is being performed on single gpu, what are the changes to do so as to train it on multiple gpus (let's say 4). (Actually I am kinda new to hydra so I am not sure how to adapt this code onto multiple gpus)

**Comment by atnikos** [comment]
Hello, actually with the current setup not many things should be needed. Just setting those flags in the `trainer/base.yaml`:
`devices=N`
`accelerator=gpu`
`strategy=ddp`
However, when I tried it, it didn't work out-of-the-box. There were some sync issues with the metrics. I am trying to make it work for my next project. You can give it a try by setting those arguments and ping me back here to help you resolve any bugs you may encounter. I don't plan to release a multi-GPU version for this but happy to help and integrate any changes that would make multi-gpu training possible.

**Comment by atnikos** [comment]
I am closing this for now feel free to re-open if you want any additional help.
