### ISSUE TITLE
problem in process_amass.py

### ISSUE THREAD

**Issue by zhuangzhuang000** [athn-nik/teach#12]
Hello! I had some problems in process_amass.py
here are three problems

![image](https://user-images.githubusercontent.com/53167695/196418178-e312e7de-b3ed-4b37-a562-af4043bd87ec.png)

---------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/53167695/196418305-5c6d274b-a39f-4b57-9605-7875f453dc0c.png)

---------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/53167695/196418472-1001f686-9a2d-48b3-bf1d-92759b6f5961.png)

**Comment by atnikos** [comment]
I have pushed some fixes can you try again and let me know?

**Comment by zhuangzhuang000** [comment]
> I have pushed some fixes can you try again and let me know?

it works! but there is still a small problem is that there is no input the args '--model_type', I set the model_type='smplh', is it right?

**Comment by atnikos** [comment]
I have removed the arg since it is not really used, pull the latest changes and it should be good to go
