### ISSUE TITLE
Quantitative results correspond to epoch #?

### ISSUE THREAD

**Issue by chinnusai25** [athn-nik/teach#13]
Can you please confirm the epoch number for which the quantitative results (APE and AVE) are provided in the paper, because it is mentioned as 600 epochs in the paper but the max_epochs in config.yaml of provided pretrained model is 1001

**Comment by atnikos** [comment]
I have reported the speed not the performance in Sup.Mat. Use either my checkpoints or if you want to retrain, just use 1000 epochs as a reasonable threshold. My experience was that with batch size 16/32 you would not see big numerical improvements over 600-700 epochs but will improve the Qual. a bit.

**Comment by chinnusai25** [comment]
Thanks for the reply, closing the issue
