### ISSUE TITLE
problem in amass_splits_babel.py

### ISSUE THREAD

**Issue by zhuangzhuang000** [athn-nik/teach#15]
I ran the amass_splits_babel.py , and get the result "Percentage not found: 879/1412", is that correct?

**Comment by atnikos** [comment]
can you give me more details about your bug? Is the process amass correctly finished? What are its results?
After that what is the exact command you run? and what the error log?

**Comment by zhuangzhuang000** [comment]
> can you give me more details about your bug? Is the process amass correctly finished? What are its results? After that what is the exact command you run? and what the error log?

I think I have found out why, when running process_amass.py, it be killed in the middle of the data processing, I continue to run, but the result amass.pth.tar file will be overwritten, so it does not contain all the data. I'm trying to get the amass.pth.tar file again.

**Comment by atnikos** [comment]
Yes, better delete that and start fresh. In that case, you should have the correct file. Let me know how it goes. Worst case, I will try to find a way to upload the processed data directly.

**Comment by atnikos** [comment]
I hope this fixes the problem. If so, ping here so I can close this.

**Comment by zhuangzhuang000** [comment]
> I hope this fixes the problem. If so, ping here so I can close this.

My computer crashed so I was delayed for a few days, the code was always killed when I was running process_amass.py, I found that the reason was not enough memory (amass data is too large), after several attempts, I finally got the complete amass.pth.tar data, re-run amass_splits_babel.py and the result is shown in the following figure.
I think this should be correct.

![image](https://user-images.githubusercontent.com/53167695/197496423-84eae654-ed56-4dd6-bb0e-73e31d5a30bb.png)

**Comment by atnikos** [comment]
Yes :) the script seems to run smoothly. I just looked at it. The percentage not found is just a statistic for the extra amass that are not included/labelled in BABEL. This will be probably done in the future

**Comment by yangzhao1230** [comment]
Hi @athn-nik , in this iussue I find the number of sequences is 14084. However, my processed sequences' number is 14022.
![image](https://user-images.githubusercontent.com/52462696/210187877-e1328639-0a36-4a6a-accc-945bf6d62a9f.png)
I wonder if I miss some data. In process_amass.py, I find the number of AMASS_DIRS is 20 (including a duplicate 'TCDhandMocap/TCD_handMocap'). 
![image](https://user-images.githubusercontent.com/52462696/210187944-9b38987d-9145-4f4d-b338-6315d3f0d591.png)
My processed suqeences exactly have 19 folders (20 - 1).
![image](https://user-images.githubusercontent.com/52462696/210187963-51c628e8-20c2-4c20-babc-3bc8ee939824.png)
I don't know where the problem occurrs. I look forward to your help.
