### ISSUE TITLE
ImportError: ('Unable to load EGL library', 'EGL: cannot open shared object file: No such file or directory', 'EGL', None)

### ISSUE THREAD

**Issue by pfeducode** [athn-nik/teach#16]
I changed the operating system. I used Centos7 to run the code, and still got the following error

![2022-10-15_16-11](https://user-images.githubusercontent.com/100210045/197339265-f8238355-680b-4ffa-827d-b67c871bb76d.png)

**Comment by atnikos** [comment]
Unfortunately, I can't reproduce the error. I have 2 suggestions yo try. 
1. `apt-get install libosmesa6-dev freeglut3-dev`
2. Comment the line where the environmental variable is set.(look at configuration(.yaml) and visualize meshes script)
Try 2. First and then 1.
Let me know if it works and I ll try to provide more help.

**Comment by pfeducode** [comment]
> Unfortunately, I can't reproduce the error. I have 2 suggestions yo try.
> 
> 1. `apt-get install libosmesa6-dev freeglut3-dev`
> 2. Comment the line where the environmental variable is set.(look at configuration(.yaml) and visualize meshes script)
>    Try 2. First and then 1.
>    Let me know if it works and I ll try to provide more help.

My operating system is Centos, so I can't execute the apt get command. I don't understand your method 2。
What operating system do you use？

**Comment by atnikos** [comment]
2: Comment line 49 in teach/render/mesh_viz.py where I set the environment variable.
1:Can you try with yum? The goal of the command is to install osmesa. It is a common problem for pyrender.

**Comment by pfeducode** [comment]
> 2: Comment line 49 in teach/render/mesh_viz.py where I set the environment variable. 1:Can you try with yum? The goal of the command is to install osmesa. It is a common problem for pyrender.

When I delete os. environment ['python_platform ']='ogl', it works well。Thank you for your patient explanation

**Comment by pfeducode** [comment]
I use [run, sit down, jump, run] to run the model. The first three actions can be executed well, but the fourth one is stuck. Why？

**Comment by atnikos** [comment]
Can you give me the command? what do you mean by stuck? are you giving the appropriate lengths?
I see you give 4 actions are you using also 4 lengths in the list length?

**Comment by pfeducode** [comment]
python interact_teach.py folder=./data/babel/babel-teach output=./results texts='[run, sit down,jump,run]' durs='[5, 3, 1,5]'
He can do the first three movements, but when he takes the fourth movement, he starts to rotate in place。
As shown in the figure below
![2022-10-15_16-11](https://user-images.githubusercontent.com/100210045/197433017-ed7fac73-3694-4e61-a29b-95f440cd2fec.png)
The video is as follows
https://drive.google.com/file/d/1fwWOegnu-Npzu40x4mia3a1nJUI3TZ5b/view?usp=sharing

**Comment by atnikos** [comment]
Ah, I see what you mean. Good to for me to know about the failure cases :) . I think that is something that has to do with the durations present in the data, can you try slightly different labels? like run forwards and smaller durations like 2-3 secs?

**Comment by pfeducode** [comment]
> Ah, I see what you mean. Good to for me to know about the failure cases :) . I think that is something that has to do with the durations present in the data, can you try slightly different labels? like run forwards and smaller durations like 2-3 secs?

Thank you for your answer
