### ISSUE TITLE
How to run the demo? No "config.yaml" found in the provided website.

### ISSUE THREAD

**Issue by RockyXu66** [athn-nik/teach#17]
When I try to run the demo, I follow the README and download the checkpoint from "TEACH" [website](https://teach.is.tue.mpg.de/download.php). But I doesn't find any configurations file like "config.yaml" in Models & Configurations part.  Any body knows how to process this?

**Comment by atnikos** [comment]
Have you tried unzipping the files and looking for a folder named `.hydra`? that folder contains all the needed configuration files.

**Comment by RockyXu66** [comment]
> Have you tried unzipping the files and looking for a folder named `.hydra`? that folder contains all the needed configuration files.

Hi nik. Thanks for your reply.
I download the `teach.zip` from this link in your website.
<img width="784" alt="image" src="https://user-images.githubusercontent.com/18605943/199643538-2c62ff7c-9af5-4701-87ab-531c62042b8b.png">

After unzipping it, I get this structure which I don't see any folder named `.hydra`.  Do you know which step I was doing wrong.
<img width="611" alt="image" src="https://user-images.githubusercontent.com/18605943/199643844-2e2be154-f3b9-48b1-9351-e7604ca5c44d.png">

**Comment by atnikos** [comment]
Can you open this path in a terminal and do ls -al ? Or try "cmd+shift+." To show hidden files in Mac?

**Comment by RockyXu66** [comment]
> Can you open this path in a terminal and do ls -al ? Or try "cmd+shift+." To show hidden files in Mac?

Oh, Sorry I forget `.hydra` is a hidden folder. I extract the zip file and successfully run the `interact_teach.py` script in my remote ubuntu machine. Thanks for your replay.

However, after running the `interact_teach.py`, I always get the same rendered results with specific `texts` and `durs` (e.g. texts=[jump, wave right hand, wave left hand] durs=[2, 2, 2]). Should I change any seed in the code or change any other things to get a different result for a fixed `texts` and `durs`?

**Comment by atnikos** [comment]
To get more diverse results you can try changing the random and most importantly change the `fact` argument in [this function ](https://github.com/athn-nik/teach/blob/dca4001d509d1f3d3e7ad2612b9ca393fee1948d/teach/model/teach.py#L250).
I didn't really dig through the diversity in this project and would be happy if you try it and let me know about the results. I can try parametrizing the demo for more diverse samples.

**Comment by atnikos** [comment]
I hope those resolved your issues, let me know if you need more help 🍻
