### ISSUE TITLE
about visualization of result

### ISSUE THREAD

**Issue by zhuangzhuang000** [athn-nik/teach#21]
Dear author,
     The video result obtained from 【interact_teach.py】shows that the character is moving in place, and the track can not be seen. How can I get the video shown in the paper (can see the track)?

**Comment by atnikos** [comment]
I have modified the visualization function to give you a better output with floor and without the body appearing to stay in place. The paper results where achieved using and modifyinf the visualization code of TEMOS. You can try using the code from that repo with my .npy samples. 
If I find time I will prepare a mini-set of instruction and clean + upload the code on how I do it for my case :)
