### ISSUE TITLE
'type' object is not subscriptable

### ISSUE THREAD

**Issue by wang-zm18** [athn-nik/teach#22]
Hello, When I tried to run the `interact_teach.py`, it just occrus this problem: 
_ImportError: Encountered error: `'type' object is not subscriptable` when loading module 'teach.model.teach.TEACH'_

The command I used is : 
`python ./teach/interact_teach.py folder=./teach output=./teach/experiments  texts='[walk, sit down, wave hands, drink water, stand up]' durs='[5,5,5,5,5]'`

Thank you in advance!

**Comment by wang-zm18** [comment]
BTW, I have placed the SMPLH_MALE.pkl in the right path.

**Comment by atnikos** [comment]
It does not have to do with SMPLh model but some imports, can you try giving the full path instead of relative?
and also post here the full error log to help you more.
does `./teach` contains the checkpoints and hydra folder?

**Comment by wang-zm18** [comment]
the path to run this command: /share/allen/teach
the command is  `python./interact_teach.py 
folder=/share/allen/teach output=/share/allen/teach/experiments  texts='[walk, sit down, wave hands, drink water, stand up]' durs='[5,5,5,5,5]'` 

The log is 

> Global seed set to 1234
> 
> [17/11/22 10:24:31][__main__][INFO] - Loading model
> Error executing job with overrides: ['folder=/share/allen/teach', 'output=/share/allen/teach/experiments', 'texts=[walk, sit down, wave hands, drink water, stand up]', 'durs=[5,5,5,5,5]']
> Traceback (most recent call last):
>   File "/share/allen/teach/teach-env/lib/python3.8/site-packages/hydra/_internal/utils.py", line 585, in _locate
>     import_module(mod)
>   File "/home/admin/miniconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/share/allen/teach/model/teach.py", line 29, in <module>
>     from teach.model.metrics import ComputeMetricsTeach
>   File "/share/allen/teach/model/metrics/__init__.py", line 1, in <module>
>     from .compute import ComputeMetrics
>   File "/share/allen/teach/model/metrics/compute.py", line 24, in <module>
>     from teach.transforms.joints2jfeats import Rifke
>   File "/share/allen/teach/transforms/__init__.py", line 2, in <module>
>     from .smpl import SMPLTransform
>   File "/share/allen/teach/transforms/smpl.py", line 25, in <module>
>     from .joints2jfeats import Joints2Jfeats
>   File "/share/allen/teach/transforms/joints2jfeats/__init__.py", line 2, in <module>
>     from .rifke import Rifke
>   File "/share/allen/teach/transforms/joints2jfeats/rifke.py", line 27, in <module>
>     class Rifke(Joints2Jfeats):
>   File "/share/allen/teach/transforms/joints2jfeats/rifke.py", line 139, in Rifke
>     def extract(self, features: Tensor) -> tuple[Tensor]:
> TypeError: 'type' object is not subscriptable
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "./interact_teach.py", line 35, in _interact
>     return interact(cfg)
>   File "./interact_teach.py", line 57, in interact
>     model = instantiate(cfg.model,
>   File "/share/allen/teach/teach-env/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 180, in instantiate
>     return instantiate_node(config, *args, recursive=_recursive_, convert=_convert_)
>   File "/share/allen/teach/teach-env/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 240, in instantiate_node
>     _target_ = _resolve_target(node.get(_Keys.TARGET))
>   File "/share/allen/teach/teach-env/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 104, in _resolve_target
>     return _locate(target)
>   File "/share/allen/teach/teach-env/lib/python3.8/site-packages/hydra/_internal/utils.py", line 587, in _locate
>     raise ImportError(
> ImportError: Encountered error: `'type' object is not subscriptable` when loading module 'teach.model.teach.TEACH'
> 
> Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by wang-zm18** [comment]
`./teach` contains the checkpoints and hydra folder indeed.
![image](https://user-images.githubusercontent.com/47704679/202340752-bf5d4fae-07d7-4c9c-998b-834d8716afb1.png)

**Comment by wang-zm18** [comment]
When I just tried `teach.model.teach.TEACH`， it directly occurs `TypeError: 'type' object is not subscriptable`

**Comment by wang-zm18** [comment]
When I just tried `teach.model.teach.TEACH` in python， it directly occurs TypeError: 'type' object is not subscriptable

**Comment by atnikos** [comment]
Hmm, the paths the you give in the command line does not match what I am seeing in the screenshot, I guess this is not so relevant with issue.
In the screenshot that I see I do not see where the teach folder is, I wonder why you have put everything in the same folder and why not in the top directory.
I would suggest doing a fresh clean installation. Download the checkpoint again and put them outside the repository and give one more try. Nobody had the problem before and it is very difficult to debug it with that setup.

**Comment by atnikos** [comment]
Hey @wang-zm18 , have you tried my suggestion?

**Comment by wang-zm18** [comment]
Thank you， I have solved this problem according to your advice!
