### ISSUE TITLE
Unable to load weights from pytorch checkpoint

### ISSUE THREAD

**Issue by arwooy** [athn-nik/teach#23]
When I run the demo interact_teach.py, got the following error:
OSError: Error instantiating 'teach.model.temos.TEMOS' : Error instantiating 'teach.model.textencoder.distilbert_transformer.DistilbertEncoderTransformer' : Unable to load weights from pytorch checkpoint file for '/root/autodl-tmp/github/teach/deps/distilbert-base-uncased' at '/root/autodl-tmp/github/teach/deps/distilbert-base-uncased/pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

**Comment by atnikos** [comment]
Have you created the environment and followed the details for git lfs using the instructions in the Readme?

**Comment by atnikos** [comment]
Hello, have you tried my suggestion @arwooy ?

**Comment by atnikos** [comment]
I am closing this since there are no updates for a long time.
