### ISSUE TITLE
Body model

### ISSUE THREAD

**Issue by yonishafir** [athn-nik/teach#26]
Hi, I've noticed your'e using "mmm" body model instead of smplh.

https://github.com/athn-nik/teach/blob/2f81b1b7e00fe279e2b4c3b557799589e8247a6a/teach/transforms/rots2joints/smplh.py#L38

I just want to make sure I understand correctly and you're indeed using it and its kinematic chain. 

I'll also be happy for a short explanation of why you choose this instead of smplh. 

Thanks.

**Comment by atnikos** [comment]
Hey @yonishafir ,

I am using `mmm` joints to follow the previous works and make sensible comparisons. As the previous papers of Ghosh et. al and L2P, TEMOS  use those and are trained on those the comparisons would not be fair.

Notice that those are used for evaluation. The whole training pipeline happens with SMPLH joints-based features. After training, I am using the `mmm` for valid comparisons and as TEACH can naturally also support SMPL rotations I am using them for visualizations (the model is actually learning body movements and not mmm skeletons as prior work). 
The conversion, which is made to enable fair evaluation, is being done as in TEMOS using this [mapping](https://github.com/athn-nik/teach/blob/2f81b1b7e00fe279e2b4c3b557799589e8247a6a/teach/info/joints.py#L36).
