### ISSUE TITLE
Out file transfer to FBX

### ISSUE THREAD

**Issue by XinandYu** [athn-nik/teach#28]
Hi.

I'd like to try the model in Unreal Engine, it seems FBX file is the fast way to do that. Is that possible to transfer the output file to a FBX file?

Or is there any other better way to do that?

**Comment by atnikos** [comment]
Can you take a look here ?

[https://github.com/vchoutas/smplx/issues/5#issuecomment-828283523](smplx-addon)

you can use the smplx add on to do this probably. Keep this open and let me know if you need more help

**Comment by XinandYu** [comment]
Sorry for the late response. The link seems not available. Could you please send it to me again?

And thanks for your help.

**Comment by atnikos** [comment]
For some reason the link does not work, can you copy paste it manually? it is accessible if you do that. And for the plugins for Unreal/Maya/Blender you can take a look at [SMPL website](https://smpl.is.tue.mpg.de/) --> news & updates section.
