### ISSUE TITLE
Preprocessing behind rfeats_mean, rfeats_std

### ISSUE THREAD

**Issue by chinnusai25** [athn-nik/teach#30]
Hey,
Thanks for your work.
I want to understand the preprocessing behind the generation of rfeats_std.pt and rfeats_mean.pt provided in teach/deps/transforms.

**Comment by atnikos** [comment]
Hello, and thanks for the nice words :)
They are used to normalize the features and are pre-computed to save some time from the users. You can find their calculation in `compute_stats.py` script.
