### ISSUE TITLE
how many pairs in dataset?

### ISSUE THREAD

**Issue by yangzhao1230** [athn-nik/teach#31]
In your paper, you mentioned:
![image](https://user-images.githubusercontent.com/52462696/211348886-f1090463-2a21-4d46-8171-929a371bb7f7.png)
However, my train set and valid set  are respectively:
![image](https://user-images.githubusercontent.com/52462696/211349129-3140579b-f0af-4063-b86c-986b6a394344.png)
![image](https://user-images.githubusercontent.com/52462696/211349200-dc5d23b0-851a-4d5e-96d9-ce88fe616ed9.png)
which are far less than mentioned in paper.
All the code about data preprocessing and spliting is based on the default setting. I wonder what causes this problem?

**Comment by yangzhao1230** [comment]
The picture of val set is missing:
![image](https://user-images.githubusercontent.com/52462696/211349970-67707c4a-3ebf-4e98-a3ed-8eb268f85f61.png)

**Comment by atnikos** [comment]
Yes, you are right see #10 , I plan to change this on the arXiv version.
