### ISSUE TITLE
where the dir "babel_v2.1"

### ISSUE THREAD

**Issue by luozhipi** [athn-nik/teach#32]
readme confused me a lot, here https://gitlab.tuebingen.mpg.de/nathanasiou/teach, it descripts babel_v2.1, but https://github.com/athn-nik/teach indicates babel-teach.

By tracing the python code, where har-coded babel_v2.1 however. can you update?

**Comment by ghost** [comment]
Hello @luozhipi ,
please do not look into other version of the code. Follow this repository. They are essentially the same version which you can download from [teach website](teach.is.tue.mpg.de)

**Comment by luozhipi** [comment]
thank you for your answer@ghost,
when I run "python train.py experiment=baseline logger=none", it requires "babel_v2.1" data, my question is where I can find this? indeed I cannot find it from TEACH download page

**Comment by atnikos** [comment]
Please try the current repo, not the gitlab one and follow the detailed instruction in the README and all your questions will be resolved.
