### ISSUE TITLE
I cannot download the Models & Configurations in project page,can you give me a Baidu Netdisk share link

### ISSUE THREAD

**Issue by jihg88** [athn-nik/teach#37]

**Comment by atnikos** [comment]
Can you tell me what is the problem ? Can you just sign in to the website and download them?

**Comment by jihg88** [comment]
It seem failed to connect the resource in my desktop,but i can download now just using my phone ,thanks for your great work!

**Comment by atnikos** [comment]
Thanks for your really nice and kind comment 🏋🏽‍♂️
