### ISSUE TITLE
where can find last.ckpt

### ISSUE THREAD

**Issue by zhohn0** [athn-nik/teach#38]
how to run demo?

**Comment by atnikos** [comment]
If you follow the instructions and go to the website teach.is.tue.mpg.de/ sign in and download the checkpoints and then follow the instructions(install the venv, put the models in the correct folders) and you are set!

**Comment by atnikos** [comment]
Any news? have you followed the instructions to download the checkpoints etc.?
I am closing this for now

**Comment by zhohn0** [comment]
> Any news? have you followed the instructions to download the checkpoints etc.? I am closing this for now

Thank you very much for your reply. I can find the checkpoints.
