### ISSUE TITLE
how to convert the joints to rotations and retarget to Mixamo?

### ISSUE THREAD

**Issue by lucasjinreal** [athn-nik/teach#39]
Hello, the npy generated seems just joints in xyz, but not typically 24,3 rotations in SMPL,
how can i using rots anyway?

**Comment by atnikos** [comment]
The generated bodies have rotations that are natively SMPL. See this answer [here](https://github.com/athn-nik/teach/issues/14#issuecomment-1283950194) you ust have to return `rots` and `trans`.
