### ISSUE TITLE
KeyError: 'test' when running python scripts/amass_splits_babel.py

### ISSUE THREAD

**Issue by Sy-Zhang** [athn-nik/teach#4]
When running ``python scripts/amass_splits_babel.py``, This Line https://github.com/athn-nik/teach/blob/0e49eaa2946958384d96f1539b4671b0222d93a3/scripts/amass_splits_babel.py#L47 reports ``KeyError: 'test'``. 

I found the problem is caused by ``dataset_db_lists``, which  does not have  ``test`` as key. https://github.com/athn-nik/teach/blob/0e49eaa2946958384d96f1539b4671b0222d93a3/scripts/amass_splits_babel.py#L32-L33

Your paper mentioned that  _"we report our final results in the validation set, for easier reproduction, since BABEL test set is not publicly available"_. Does it mean all ``test`` sequences are discarded here?

**Comment by atnikos** [comment]
You are right, I forgot to omit the test set from the process.

**Comment by Sy-Zhang** [comment]
Thanks for answering!
