### ISSUE TITLE
interact run error

### ISSUE THREAD

**Issue by lucasjinreal** [athn-nik/teach#40]
```
 module named 'pyrender'
No module named 'pyrender'
[05/05/23 15:49:50][HYDRA] C:\ProgramData\miniconda3\lib\site-packages\hydra\_internal\hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(

Global seed set to 1234
[05/05/23 15:49:50][__main__][INFO] - Loading model
Error executing job with overrides: ['folder=.\\pretrained_models\\teach\\', 'texts=[a man is walking and then jump]', 'durs=[123]', 'output=res']
Error in call to target 'teach.model.teach.TEACH':
InstantiationException('Error in call to target \'teach.model.textencoder.text_hist.TextHist\':\nValueError("\'deps\' is not in list")\nfull_key: textencoder')
full_key: model

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

**Comment by atnikos** [comment]
Please check the instructions and install the environment properly before proceeding.

**Comment by lucasjinreal** [comment]
@athn-nik  Hello, I just followed the instructions, I don't know why it claims this error ,what I miss here?

**Comment by atnikos** [comment]
Actually I see that you are using conda and don't have pyrender. If you had followed the instructions and run `source scripts/install.sh` you would have a neat python environment with all the dependencies there. So, either do that or pip install the requirements manually by looking at the script I cited above.

**Comment by lucasjinreal** [comment]
@athn-nik pyrender I manually try catched since i am on windows, should pyrender effect hydra config problem? it shouldn't, the error messages is about hydra. Am using conda but it should meet all requirements it need, I can run TEMOS on my env.

**Comment by lucasjinreal** [comment]
@athn-nik hello, how can I further debug this issue, am totally don't know how hydra give me this error. is that import error? lack of `__ini__.py` or something? I am missed out here!

**Comment by atnikos** [comment]
I have tested this code only on Linux so I am not really an expert but I can help. No module named `pyrender ` says that this is not installed. I don't think TEMOS used pyrender for renderings. You can try `python` inside that environment and then `import pyrender`. Does that work? TEMOS environment is different than TEACH environment.

**Comment by lucasjinreal** [comment]
@athn-nik  I manually catched pyredner import error since windows not possible using pyrender (its very old and can not installed really), it shouldn't matter other code run.
