### ISSUE TITLE
where I can find amass-path2babel.json?

### ISSUE THREAD

**Issue by JacopoDapueto** [athn-nik/teach#48]
Hello, I'm following the instructions for recreating the Babel dataset. As suggested in the Readme, I downloaded the AMASS dataset and the SMPLH body models, then I processed the dataset with _scripts/process_amass.py_. Now I have to split the dataset with _scripts/amass_splits_babel.py_, and it requires a file **amass-path2babel.json** that defined the splits. Where can I find such file?

Thanks in advance for the help

**Comment by atnikos** [comment]
I guess you have found this file, right? It is supposed to be downloader!
