### ISSUE TITLE
Error occured when try to load checkpoint provided in "independent-bsl"

### ISSUE THREAD

**Issue by Xiyan-Xu** [athn-nik/teach#5]
When I try to run command:
`
python interact_teach.py folder=TrainedModels/independent-bsl output=RenderResults/dance texts='[dance, standing, turns left]' durs='[3.7, 3, 2]'
`
Error occurs, stating that "no module named teach.model.teach.TEMOS"
After I change the config __target__ to "teach.model.temos.TEMOS" mannually, there is still an error:
`
ImportError: Error loading module 'temos.model.motiondecoder.ActorAgnosticDecoder'
`
I think there is something wrong in the ckpt file, maybe independent-bsl is recorded in a different file system

**Comment by atnikos** [comment]
You are right, I will check the checkpoints, re-upload it and fix this soon. I will leave this issue open and update here.

**Comment by Stomachache007** [comment]
> You are right, I will check the checkpoints, re-upload it and fix this soon. I will leave this issue open and update here.

Wait for your fix, thanks.

**Comment by atnikos** [comment]
@Stomachache007 , @Ajatar213455 does the teach checkpoint and config work for you?

**Comment by atnikos** [comment]
I have reuploaded the files in website with the needed fixes. Please @Stomachache007 , @Ajatar213455  re-download them and run it again. They run smoothly on my side for all 3 models.

**Comment by Stomachache007** [comment]
> I have reuploaded the files in website with the needed fixes. Please @Stomachache007 , @Ajatar213455 re-download them and run it again. They run smoothly on my side for all 3 models.

It works for me now !
